name: recipevox_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1 
  cloud_firestore: ^5.6.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.1.0
  form_field_validator: ^1.1.0
  fluttertoast: ^8.2.2
  material_floating_search_bar: ^0.3.7
  flutter_svg: ^2.0.17
  sqflite: ^2.3.0
  path: ^1.8.3
  picovoice_flutter: ^3.0.4
  flutter_voice_processor: ^1.0.6
  just_audio: ^0.9.34
  text_to_speech: ^0.2.3
  vosk_flutter_plugin:
    git:
      url: https://github.com/alphacep/vosk-flutter.git
      ref: e752836c669b11ae72de2deefdfe9fced32881ec
  image_picker: ^1.0.4
  firebase_storage: ^12.4.2
  tflite_flutter_helper: ^0.3.1
  hooks_riverpod: ^2.3.2
  simple_logger: ^1.9.0+2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/makeat_transparent.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/svgs/
    - assets/sqlite/
    - assets/vosk/
    - assets/miss_chef_ai_model/
